tools/build_release_uvision.bat

Clear output dir at outset to ensure all resulting artifacts are new
Use /B in exit command otherwise the script closes the console window when it completes. The previous behavior proved to be quite the pain. I'd run the script, and eventually the console would close, leaving me unable to see if the build failed or succeeded.

build script improvements

---

test/run_test.py

WindowsError, not CalledProcessError, is thrown on Windows when subprocess.Popen() fails due to executable not found. The scripts fails to display a simple, helpful message; user gets a stack trace.
Also various improvements to messages

Uncaught exception when git not in PATH on Windows

---

docs/DEVELOPERS-GUIDE.md
tools/build_release_uvision.bat

Forgot to fix both exit lines in earlier pull request.
Without the /B, the window console closes when the script end, and the user has no real chance to see what happened.

Use /B to avoid closing console

---

test/daplink_firmware.py
test/run_test.py

The test logic was requiring a target executable even when --notestendpt was specified. The target binary is used only by the endpoint testing.

Fix --notestendpt handling

---

requirements.txt

Use a progen version below 0.9.0 since this introduces a bug preventing
some configurations of DAPLink from building.

Update requirements.txt to fix build problems

---

source/daplink/drag-n-drop/vfs_user.c
source/daplink/drag-n-drop/virtual_fs.c

To allow space for larger devices increase the filesystem to 64MB.
To do this the filesystem has been switched to FAT16.

Increase FS size to 64MB and use FAT16

---

source/usb/msc/usbd_msc.c
source/usb/usb_lib.c
source/usb/usbd_msc.h

If a USB reset occurs in the middle of a SCSI command
mass storage can get in a state where it thinks the transfer
is still ongoing.  This cases new SCSI commands to get ignored
by the device.  This causes the PC to disable the MSC endpoint.
This patch fixes that problem by properly resetting the MSC endpoint
when a USB reset occurs.

Reset MSC endpoint on USB reset to fix bug

---

source/hic_hal/freescale/k20dx/uart.c
source/hic_hal/freescale/kl26z/uart.c
test/serial_test.py

If a uart interrupt comes in at the right time then
write_buffer.cnt_out can get incremented twice.  This causes the TX
interrupt to get stuck in a state where it is constantly transmitting
data.
This patch fixes that race condition by incrementing
write_buffer.cnt_out in just one place - the uart interrupt.

Fix K20DX uart race condition

---

requirements.txt
source/hic_hal/freescale/k20dx/armcc/startup_MK20D5.s
source/hic_hal/freescale/kl26z/armcc/startup_MKL26Z4.s

Use pre-processor syntax in startup_MK20D5.s rather than the
assembler specific configuration syntax.  This make DAPLink compatible
with the more recent versions of progen which only use preprocessor
options.

Add support for progren version 0.8.16 and above

---

projects.yaml
records/tools/make_armcc.yaml
requirements.txt
source/daplink/RTX_Config.c
source/daplink/cortex_m.h
source/daplink/drag-n-drop/vfs_manager.c
source/daplink/drag-n-drop/vfs_user.c
source/hic_hal/freescale/iap/FlashDev.c
source/hic_hal/freescale/iap/FlashPrg.c
source/hic_hal/freescale/kl26z/read_uid.c
source/target/nordic/target_reset.c
tools/post_build_script.sh
tools/pre_build_script.py
tools/pre_build_script.sh

Also adds a sh build script.
Works as expected on Linux (Ubuntu 14.04).

Build with the progen make_armcc tool

---

test/hid_test.py

Remove all the the target specific information from hid_test.py and
instead grab this info from pyOCD.

Remove target info from hid test

---

source/daplink/cmsis-dap/SW_DP.c

When an SWD protocol error occurs the SWDIO line is unintentionally
left in input mode. This causes further transactions to fail.
This patch corrects this by setting SWDIO to output after a protocol
error. This also aligns with the more recent versions of CMSIS-DAP
(CMSIS-SP-00300-r4p5-00rel0) which contain this change.

Fix bug with handling SWD protocol errors

---

docs/PORT_BOARD.md
test/daplink_firmware.py
test/firmware.py
test/info.py
test/run_test.py
test/target.py

Update the testing framework to properly handle firmware that can
change board IDs based on the board it is loaded on.  To allow this
the different configurations to be tested are hard-coded in info.py.
This allows boards, targets and firmware to be decoupled.

Update testing to allow same fw on several boards

---

source/hic_hal/atmel/sam3u2c/uart.c

Add code to flush the UART buffers when the baud rate is changed.
This fixes a bug in mbed testing where serial data on a failed test
can show up in a subsequent test.

atsam3u - Flush uart buffers on baud rate change

---

test/serial_test.py

Create a SerialTester class to wrap common serial port operations.
Use this class to remove extra copy-paste code.

Update serial test to make test cases modular

---

source/hic_hal/atmel/sam3u2c/uart.c

Update the hal implementation of the sam3u2c to return the actual number of bytes free in the CDC buffer. Previous behavior returned that there was no space in the buffer if there were any bytes in it.

sam3u2c - return real free write size in uart buf

---

test/info.py

Add the lpc4088 quick start board and display module board to the release.

Add lcp4088 boards to release

---

test/daplink_board.py

On OSX mbed-ls can return null for some endpoints at times. This patch updates the code to gracefully handle this.

Fix mbedls on mac

---

records/hic_hal/k20dx.yaml
records/hic_hal/kl26z.yaml
source/daplink/util.h

Do not include filename in asserts in the bootloader, to save code size. This fixes the K20DX128 bootloader build failure caused by the code size being >0x7c00 when the flash driver is updated to the latest version in KSDK 2.0 (see #128).

Exclude assert filenames from bootloader

---

source/hic_hal/nxp/lpc11u35/usbd_LPC11Uxx.c

The pin PIO0_3 is used on some boards for USB voltage detection. This is typically used in conjunction with a voltage divider to bring 5v to 3.3v. The software pulldown on this pin can interfere with this voltage divider and on some boards this prevents detection of a USB connection. This patch removes this pulldown to allow those boards to operate normally.

lpc11u35 - Improve USB voltage detection

---

source/hic_hal/nxp/lpc11u35/usbd_LPC11Uxx.c

If USBD_WriteEP is called before the BUF_ACTIVE bit is cleared in the current endpoint then the code will get stuck in an infinite loop. This is because "ptr" is not volatile so the value it is pointed to is only
read once. This patch fixes that infinite loop by making the "ptr" variable volatile.

Fix lpc11u35 lockup in USBD_WriteEP

---

source/hic_hal/freescale/k20dx/DAP_config.h

- Enable high drive strength for SWD pins on the K20DX128 HIC.
- Fix problem with nRESET being driven when SWD was disabled on the K20DX128 HIC. This resolves a long standing problem where you couldn't use DAPLink for the virtual serial port while simultaneously using another debug probe connected to the target SWD header.

K20DX128 HIC pin fixes

---

source/daplink/drag-n-drop/flash_manager.c
source/daplink/drag-n-drop/flash_manager.h
source/daplink/drag-n-drop/iap_flash_intf.c
source/daplink/interface/target_flash.c
source/target/unsupported/atmel/target_flash.c
source/target/unsupported/renesas/target_flash.c

The drag-n-drop programming function currently does a mass erase when re-programming a target device. Having it do a sector erase will prevent bootloader/ROM code already in the flash from being erased.

[Flash] Make the drag-n-drop do a sector erase instead of mass.

---

source/daplink/drag-n-drop/vfs_manager.c

When a file with a '.bin' or '.hex' extension is found then the remount
timer starts. Abort the remount if the file is deleted before any data
is sent.
When copying files with attributes that do not exist on FAT16 windows
goes through the following steps:
1. Create an uninitialized file of the correct size
2. Delete the file created in step 1
3. Create new file with size 0
4. Prompt user:
"Are you sure you want to copy this file without its properties"
5. If yes then send file data, if no the delete file
This causes problems because after the file in step 1 is deleted
DAPLink detects this as a transfer error and remounts. By aborting
the transfer instead of triggering an error files with incompatible
attributes can be properly copied.
This problem can be reproduced by saving a target …

Don't remount if file is deleted before data sent

---

projects.yaml
records/board/nina_b1.yaml
source/board/nina_b1.c
source/board/override_mkl26z_reset/IO_Config_Override.h
source/hic_hal/freescale/kl26z/IO_Config.h
test/info.py

Adding u-blox NINA-B1 based board target. The DAPLink HDK is utilizing a KL26z.

Adding NINA-B1 target board

---

test/serial_test.py

I was getting an exception when setting the timeout. The code reads to flush out any leftover data, but changing the timeout when something is in the queue causes an exception. 
`
File "DAPLink/test/serial_test.py", line 144, in set_read_timeout
assert self._queue.empty(), "Queue must be empty to change timeout"
AssertionError: Queue must be empty to change timeout
`

[Test] Moving the setting of serial timeout.

---

source/daplink/interface/swd_host.c

`swd_read_block()` was always causing the AP to issue a read of an extra word.
This is the root cause of the problem that was also addressed by #189. On Kinetis devices where the UID is read, the bug causes the word after the last UID register, an invalid register on most devices, to also be read. (#189 is still useful on its own, will continue to work on it.)
Verified that the UID is still successfully read as the same value before and after the patch.
Also replaced some literal constants in `swd_read_block()` with macros to improve readability.

Fix erroneous read of extra word in swd_read_block()

---

source/hic_hal/nxp/lpc11u35/gpio.c

When entering ISP mode from a running application the main stack (MSP) is set to the correct value, but the processor is still running using the process stack (PSP). This causes a crash in ISP mode. This patch fixes this by switching the current stack to the MSP before jumping to ISP mode.

lpc11u35 - fix entering ISP mode from application

---

source/hic_hal/nxp/lpc11u35/uart.c
source/hic_hal/nxp/lpc11u35/usbd_LPC11Uxx.c

When a SETUP packet comes immediately after a control transfer with a data in stage there is a chance that the OUT packet sent by the host at the end of the transfer will be dropped. This is because there is no way to tell that the SETUP and OUT are both pending so only the SETUP packet gets processed.
This patch records whether an OUT packet is expected or not on the control endpoint. If it is then it ensures that the OUT packet is processed first.

lpc11u35 - Prevent dropped USB SETUP packets

---

source/daplink/util.h

Asserts can be disabled to save space. This should only apply to the bootloader since the interface has enough space for asserts.

Only disable asserts for bootloader

---

source/daplink/drag-n-drop/vfs_manager.c

Stop further file processing once a mass storage transfer is finished. This fixes an assert sometimes caused when data arrives after a transfer has been completed.

Fix msd assert caused by processing after xfer

---

source/daplink/drag-n-drop/vfs_user.c

Display the number of remounts as a value in details.txt. This allows test scripts to determine if a remount actually occurred.

Keep track of number of remounts in details.txt

---

source/daplink/cmsis-dap/usbd_user_hid.c
source/daplink/interface/main.c
source/daplink/interface/main.h

Move the HID response to the main thread. This ensures that all HID USB operations are done on the same thread.

Synchronize hid by moving it to main thread

---

docs/MSD_COMMANDS.md
source/daplink/circ_buf.c
source/daplink/circ_buf.h
source/daplink/drag-n-drop/vfs_user.c
source/daplink/settings/settings.h
source/daplink/settings/settings_rom.c
source/daplink/settings/settings_rom_stub.c
source/hic_hal/atmel/sam3u2c/uart.c
source/hic_hal/freescale/k20dx/uart.c
source/hic_hal/freescale/kl26z/uart.c
source/hic_hal/nxp/lpc11u35/uart.c
tools/generate_config.py

Update all uart drivers to use a common queue driver for TX and RX. Update overflow behavior so once DAPLink's RX buffer has filled further characters are dropped. Also add the message "<OVFL>" to the
serial data if an overflow condition occurs.

Improve fifo overflow

---

source/daplink/interface/main.c
source/hic_hal/nxp/lpc11u35/gpio.c

Update the lpc11u35's led driver so GPIO_LED_ON corresponds to an led that is turned on.  Update main.c so when there is no endpoint activity the endpoint LED defaults to off rather than on.

Update led code to match hardware

---

source/daplink/interface/swd_host.c
source/daplink/interface/swd_host.h
source/daplink/interface/target_flash.c
source/target/nordic/target_reset_nrf5x_sam3u2c.c

This reverts commit c074a58052873296fa9f918341cb0e06e6ab0c03. This is reverted because it causes some lpc targets such as the lpc812 to enter a bad state after programming, since the DP is turned off while the debug logic is still enabled.

Revert "Added swd_uninit_debug() function. Used new function in reset…"

---

tools/package_release_files.py

The package release script incorrectly handles underscores in the base name of firmware. Instead of getting the whole name it only grabs up to the first underscore. For example for the base name of 'sam3u2c_mkit_dk_dongle_nrf5x_if' is determined to be 'mkit' rather than 'mkit_dk_dongle_nrf5x'. This patch fixes that problem by joining the middle elements of the name to create the correct base name.

Fix release package script to handle underscores

---

source/usb/msc/usbd_msc.c

Correct asserts that were triggering incorrectly.

Mass storage assert fixes

---

docs/DEVELOPERS-GUIDE.md

Remove the quotes from the windows commands for starting a virtualenv. This allows the command to work in git shell in addition to cmd.

Update virtualenv docs to work for more setups

---

source/daplink/interface/target_flash.c

If automation is enabled then read back every page written to verify the contents are correct. This allows devices with worn out flash to be detected.

Verify data flashed when automation is enabled

---

test/stress_tests/cdc_stress_test.py
test/stress_tests/hid_usb_test.py
test/stress_tests/msd_remount_test.py

Add a stress test script script for each mass storage endpoint. Each script tests all attached DAPLink boards at the same time. All three scripts can be running at the same time. To determine that a CI setup is stable these three tests should be run at the same time with multiple boards attached for 1+ hour (ideally 24+ hours).

Add stress test scripts

---

source/hic_hal/atmel/sam3u2c/uart.c
source/hic_hal/freescale/k20dx/uart.c
source/hic_hal/freescale/kl26z/uart.c
source/hic_hal/nxp/lpc11u35/uart.c

When overflow detection is not turned on and and overflow occurs drop the oldest rather than the newest data. Newest data is still dropped if overflow detection is turned on.

Drop oldest character on UART overflow

---

test/msd_test.py
test/test_info.py

Under certain conditions a PC running DAPLink tests can clear the disk cache DAPLink is mounted on. When this occurs the host OS will re-read disk contents. Since DAPLink's disk contents never change the
drive will look like it did when it first mounted. None of the new files that were created will exist. If this cache clear occurs in the middle of a write operation in the mass storage test an IOError will be raised, causing testing to terminate abruptly.
To prevent testing from spuriously failing this patch adds retry logic to the mass storage test. This prevents these spurious failures.
Note - a disk cache clear can be triggered by allocating most of the systems memory in a program. For example on a windows 10 PC with 16GB of RAM running the following code (which allocates 15GB) in a …

Add retry logic to mass storage test

---

source/daplink/cmsis-dap/DAP.c
source/hic_hal/atmel/sam3u2c/read_uid.c

Fix incorrect flash settings causing core to run at 1/4th normal speed. Remove SWJ clock customizations since the core is running at the correct speed.

Atsam3u clock fix

---

source/hic_hal/freescale/kl26z/gpio.c

Add short delay to allow for delays between split power sources for target and debugger.
Otherwise if target power supply is late then it keeps entering the maintenance mode if NRESET_FB_ISP is not detected high.

Add short startup delay to gpio_init like in k20dx port.

---

source/hic_hal/atmel/sam3u2c/usbd_ATSAM3U2C.c
source/usb/msc/usbd_msc.c

Fix a problem with the atsam3u and a generic problem causing CBW packets to get stalled if they occur at the right time.

More usb fixes

---

requirements.txt
source/daplink/cmsis-dap/dap_vendor_command.c
source/daplink/interface/main.c
source/daplink/interface/main.h
test/run_test.py
test/test_info.py
test/usb_cdc.py
test/usb_hid.py
test/usb_msd.py
test/usb_test.py

Add tests at the USB level to reproduce and test for problems that can't be reliably reproduced when using the host msd,  cdc and hid drivers. Also, add a DAPLink USB test command to simulate worst case device USB driver latency.

Pyusb testing

---

test/target.py

When loading a bundle of targets, don't assert if the target isn't used. This allows new targets to be added in advance before DAPLink work starts.

Don't assert on unused targets when testing

---

records/board/mkit_dk_dongle_nrf5x.yaml
source/board/override_mkit_dk_dongle_nrf5x/IO_Config_Override.h
source/hic_hal/atmel/sam3u2c/DAP_config.h
source/hic_hal/atmel/sam3u2c/IO_Config.h
source/hic_hal/atmel/sam3u2c/gpio.c

Make the IO of the atsam3u compile time configurable to support boards with slight pinout variations.

Configurable IO on atsam3u

---

source/hic_hal/atmel/sam3u2c/uart.c
source/hic_hal/freescale/k20dx/uart.c
source/hic_hal/freescale/kl26z/uart.c
source/hic_hal/nxp/lpc11u35/uart.c
source/hic_hal/uart.h

Add the function uart_enable_flow_control() which allows flow control to be explicitly enabled or disabled. By default flow control is on on the platforms which support it.

Add runtime option to enable uart flow control

---

source/usb/cdc/usbd_cdc_acm.c

Fix problems that occur when serial data is sent by the target while DAPLink is booting.

Fix serial problems

---

source/daplink/usb2uart/usbd_user_cdc_acm.c

During UART break, target device is set to reset. UART may capture noise as data during this reset period. Disable UART and initialize it back when device is out of reset.

Disable UART when target device in reset state

---

source/hic_hal/atmel/sam3u2c/usbd_ATSAM3U2C.c

When in high speed mode, the atsam3u hal drops start of frame SOF interrupts. This causes a MICRO_SOF rate 1/8 slower than it should be since SOF and MICRO_SOF never occur at the same time. This patch fixes that problem by processing SOF interrupts in addition to MICRO_SOF interrupts.
Note - When in USB test mode during the USB tests, the timing occasionally caused the atsam3u to only receive SOF interrupts and no MICRO_SOF interrupts for more than 10s at a time. When in this state the CDC port would stop sending UART data to the host PC, since CDC IN transfers are started on the start of frame handling which was only triggered by a MICRO_SOF interrupt. This caused an intermittent serial read timeout in the when running the all endpoint test. With the addition of processing SOF …

Fix USB uframe rate on atsam3u

---

docs/BOOTLOADER_UPDATES.md
records/hic_hal/k20dx.yaml
records/hic_hal/kl26z.yaml
records/hic_hal/sam3u2c.yaml
source/daplink/bootloader.h
source/daplink/interface/bootloader_update.c
source/daplink/interface/main.c
tools/build_release_uvision.bat
tools/copy_release_files.py
tools/post_compute_crc.py

Allow bootloader builds to be created by defining DAPLINK_BOOTLOADER_UPDATE. When this is defined the bootloader image will be built into the interface. When the interface runs for the first time it will update the bootloader.

Add framework for bootloader updates

---

projects.yaml
records/board/ublox_evk_nina_b1.yaml
source/board/override_ublox_evk_nina_b1/IO_Config_Override.h
source/board/ublox_evk_nina_b1.c
source/target/nordic/target_reset_nrf5x_sam3u2c.c
test/info.py

I have only done some manual tests to verify that serial, MSD and debugging works since we don't have the Keil uvision compiler. The binaries have been built with ARMCC(make_armcc project) instead but the automatic tests seems quite tricky to run without uvision.

Add ublox evk nina b1 board

---

projects.yaml
records/board/vbluno51.yaml
source/board/override_vbluno51/IO_Config_Override.h
source/board/vbluno51.c
source/hic_hal/nxp/lpc11u35/uart.c
test/info.py

Add support for the VBLUno51 board
Email from Sarah Marsh (mbed):
************************************
Hi,
Here is your daplink board ID: C006
The slug: VBLUNO51
When I execute mbedls, it looks like you have used the DAPLink ID for the NRF51_DK. You need your own unique ID. We are running the tests with the NRF51_DK ID mocked as your platform, but you will need to do the following to be mbed enabled:
Please submit a PR against mbed-ls (https://github.com/ARMmbed/mbed-ls), so your board can be detected with our tools.
Please also submit a PR against DAPLink (https://github.com/mbedmicro/DAPLink), so that your board is uniquely identifiable.
Thanks,
Sarah
************************************
The VBLUno51 board was added to mbed-os 5.5.2 released
https://github.com/ARMmbed/mbed-os/pull/4629 …

Add support for the VBLUno51 board

---

test/daplink_firmware.py

Verify if project path is a directory.
This fixes ".DS_Store" problem on macOS.

Fix ".DS_Store" problem on macOS

---

test/daplink_board.py
test/run_test.py

Before we start testing, a set of functions may validate and fix environment
where necessary and possible.
This fixes intermittent missing bootloader blocking issue.
Test suite will search for broken bootloader artifacts and fix where possible.

Test: BL is flashed before IF when --loadbl set. 

---

docs/DEVELOPERS-GUIDE.md

mbed-ls is required by DAPLink, but the install scripts of mbed-ls doesn't support Python3 now.

Update Python version requirement

---

source/daplink/interface/swd_host.c

On each flash algorithm call the flash algorithm blob is copied to ram. This is unnecessary and slows down flash programming. This patch removes the code in swd_write_debug_state responsible for this copy on every flash algo call.

Only copy flash algo to ram once

---

source/board/k20dx_bl.c
source/board/kl26z_bl.c
source/board/lpc4322_bl.c
source/board/sam3u2c_bl.c

Ensure a device's memory map is kept in sync with its device info by using memory map defines and asserting on an unintended change.

Base IAP device info on memory map

---

source/board/vbluno51.c

For mbed Online Compiler because the VBLUNO51 use nrf51822 target
Signed-off-by: iotvietmember <robotden@gmail.com>

Disable UART HWFC

---

source/target/freescale/kl82z/target.c

Fix typo in target_device for the kl82z. This fixes programming for this device.

Fix ram end for kl82z

---

source/daplink/interface/main.c
source/hic_hal/atmel/sam3u2c/gpio.c
source/hic_hal/freescale/k20dx/gpio.c
source/hic_hal/freescale/kl26z/gpio.c
source/hic_hal/gpio.h
source/hic_hal/nxp/lpc11u35/gpio.c
source/hic_hal/nxp/lpc4322/gpio.c

Previously the K20DX128 HIC would immediately enable the target power switch in `gpio_init()`. This can cause problems with certain computers on boards (i.e., upcoming MIMX6RT1050-EVK) that have high inrush currents. This change causes the interface to wait until USB is configured to turn on the power switch.
- Added `gpio_handle_usb_connected()` to gpio.h. This is is stubbed out for all HICs other than K20.
- Interface main function calls `gpio_handle_usb_connected()` when USB is configured, and when it is about to be disconnected. The bootloader is not modified.
- The K20 HIC implements this function to enable the target power switch only after high power has been negotiated with the USB host. It also turns off the power switch if USB is being disconnected.

K20 HIC waits until USB is configured to enable target power

---

test/test_info.py

This will generate a timestamp prefix on each testing log output/file line, in a format used by wireshark / USBDump, to correlate testing logs and USB bus events, thus improving analysis of the logs.
This was already applied and tested before in https://github.com/mbedmicro/DAPLink/tree/experimental_ci_changes..

Added timestamp prefix for test_info() logging.

---

source/hic_hal/atmel/sam3u2c/flash_hal_SAM3U.c
source/hic_hal/freescale/iap/FlashPrg.c

Update the atsam3u and kinetis flash drivers so they disable interrupts when erasing or programming flash. This prevents a crash from occurring if an interrupt occurs during flashing when the flash cannot be read.
This also fixes a watchdog reset on K20 interfaces which occurs when an interrupt interrupts the watchdog unlock sequence in the flash "Init" function.  The addition of this critical section prevents the watchdog operation from being interrupted.

Disable interrupts when performing flash ops

---

source/hic_hal/atmel/sam3u2c/usb_config.c
source/hic_hal/freescale/k20dx/usb_config.c
source/hic_hal/freescale/kl26z/usb_config.c
source/hic_hal/nxp/lpc11u35/usb_config.c
source/hic_hal/nxp/lpc4322/usb_config.c

The file usb_config.c has checks to ensure the same endpoint is not used for two different interfaces. This check has a mistake where USBD_HID_EP_INTIN is being checked against USBD_MSC_EP_BULKIN twice and not checked against USBD_MSC_EP_BULKOUT. This patch corrects the check.

Fix endpoint conflict check

---

source/daplink/interface/swd_host.c

Remove first hardware reset sequence that caused some issues on K64F while flashing new firmware while old was already starting up.

Fix reset-run before reset-flash.

---

tools/pre_build_script.bat
tools/pre_build_script.py

This change is to prevent always rebuilding vfs_manager.c and vfs_user.c.
`pre_build_script.bat` only copies `version_git_tmpl.txt` if the call to `python --version` returns an error. `pre_build_script.py` no longer deletes `version_git.h`, and only overwrites it if the content would change.

Only update version file if it changes

---

test/msd_test.py

The remove the print of a test_info object, as this information is not useful.

Remove unnecessary print of test_info

---

source/daplink/bootloader/main.c
source/daplink/drag-n-drop/vfs_user.c
source/daplink/interface/main.c
source/daplink/interface/main.h
source/hic_hal/atmel/sam3u2c/gpio.c
source/hic_hal/freescale/k20dx/gpio.c
source/hic_hal/freescale/kl26z/gpio.c
source/hic_hal/gpio.h
source/hic_hal/nxp/lpc11u35/gpio.c
source/hic_hal/nxp/lpc4322/gpio.c
source/hic_hal/target_reset.h

Rather than handling forwarded reset in on vendor specific code, instead handle this at a common layer. To do this, this patch adds the functions gpio_get_reset_btn_no_fwrd() and gpio_get_reset_btn_fwrd() which are far easier to implement.

Simplify reset button handling

---

source/board/mkit_dk_dongle_nrf5x.c
source/target/nordic/nrf5x/target.c
source/target/nordic/target_reset_nrf5x_sam3u2c.c

Based on pins PB1, PB2, PB3, set board id to 1102 for NRF52840-DK.
Signed-off-by: Kyle Stein <kyle.stein@arm.com>

Add support for NRF52840-DK board

---

source/daplink/interface/target_flash.c

If a device's sector is smaller than 256 bytes then set the minimum programming size to the sector size rather than asserting.

Support devices with sectors less than 256 bytes

---

source/target/freescale/target_reset_Kseries.c

Remove the code which performs a reset on boot since this risks corrupting any nonvolatile storage on the target device. This code is for reading the target ID and is no longer used.

Fix Kinetis K series reset on boot

---

source/board/frdmk64f.c
source/daplink/interface/target_flash.c
source/hic_hal/flash_blob.h
source/hic_hal/target_config.h
source/target/freescale/k64f/flash_blob.c
source/target/freescale/k64f/target.c

Cherry pick #374 to master to re-enable sector erase on the K64F. This was initially reverted in #386.

Unrevert K64F sector erase change

---

source/daplink/interface/swd_host.c
source/daplink/interface/target_flash.c
source/hic_hal/target_reset.h
source/target/freescale/target_reset_Kseries.c
source/target/freescale/target_reset_Lseries.c

Make changes to allow targets to be halted without a reset occurring:
- Reset after programming to update state
- Remove reset in Kinetis debug init
- Add options to HALT and RUN,

Allow target to be halted without being reset

---

source/daplink/drag-n-drop/vfs_user.c
source/daplink/error.c
source/daplink/error.h
test/daplink_board.py
test/msd_test.py
test/test_daplink.py

This patch adds error type information to FAIL.txt in case of failures to flash.
e.g.
currently in FAIL.txt
File sent out of order by PC. Target might be programmed correctly.
new FAIL.txt
error: File sent out of order by PC. Target might be programmed correctly.
error type: transient, user

Add error type to FAIL.txt

---

source/daplink/interface/swd_host.c

Failures were seen when swd_init() was called in the RUN state.
This needs to be investigated further. Issue#416 has been created
to track this.
Signed-off-by: Mahesh Mahadevan <mahesh.mahadevan@nxp.com>

Avoid calling swd_init() when invoking the RUN state

---

projects.yaml
records/board/mtb_usi_wm_bn_bm_22.yaml
source/board/mtb_usi_wm_bn_bm_22.c
source/target/st/stm32f412rg/flash_blob.c
source/target/st/stm32f412rg/target.c
test/info.py

Add the files necessary for the USI WM-BN-BM-22. Flash algo was taken from stm32f412re but the flash is sized for +1mb.

Add support for the USI WM-BN-BM-22

---

source/daplink/interface/swd_host.c

The issue was uncovered when issuing a SYSTEM RESET on the i.MXRT platform.
Signed-off-by: Mahesh Mahadevan <Mahesh.Mahadevan@nxp.com>

Keep interrupt priority group value unchanged when writing to the AIRCR register

---

source/daplink/cmsis-dap/usbd_user_hid.c
source/daplink/interface/main.c

Synchronously handle HID set report so that HID get report is always able to send the result of HID set report. This also simplifies the code and saves rom since the dedicated HID thread is no longer needed.
I tested performance to make sure there were no regressions:
pyOCD programming before this PR:
INFO:root:Programmed 819200 bytes (200 pages) at 45.05 kB/s
INFO:root:Programmed 819200 bytes (200 pages) at 44.99 kB/s
INFO:root:Programmed 819200 bytes (200 pages) at 46.38 kB/s
pyOCD programming with this pr:
INFO:root:Programmed 819200 bytes (200 pages) at 44.70 kB/s
INFO:root:Programmed 819200 bytes (200 pages) at 46.45 kB/s
INFO:root:Programmed 819200 bytes (200 pages) at 46.11 kB/s

Improve handling of HID set and get report

---

source/target/freescale/rapid_iot/target_reset.c

When the Kinetis flash is empty the reset line toggles. This causes failures when trying to halt the target. Use the reset halt method in this case.

Rapid-IoT: Update implementation to HALT target

---

test/info.py

Release the KL82Z firmware for offset 0x5000 rather than 0x8000 since it the FRDM-KL82Z ships with OpenSDA 2.0.

Correct KL82Z release offset

---

test/msd_test.py

Add a delay before copying files on to DAPLink to allow Windows 8 and Windows 10 to complete any indexing it needs to do when a device is connected.

Fix Windows testing failures due to indexing

---

source/usb/usb_lib.c

USB descriptor is broken on Windows 10 machine after latest WebUSB Pull request. It is because order of interfaces is important on Windows machine. This PR fixes this behaviour.
@c1728p9

Fix interfaces order.

---

source/board/microbit.c
source/hic_hal/freescale/kl26z/IO_Config.h

Pin 20 on the micro:bit KL26 has a no-fit part for an external-pull in v1.3 of the board (so it is left floating), and this external pull up is fitted in v1.5.
This PR sets the internal pull down on pin20, identifies the board and sets the respective `board_id ` based on the pin20 digital read.

microbit: Autodetect board type on runtime

---

records/board/microbit.yaml
source/daplink/cmsis-dap/usbd_user_hid.c
source/daplink/drag-n-drop/vfs_manager.c
source/daplink/interface/main.c
source/daplink/interface/main.h
source/daplink/usb2uart/usbd_user_cdc_acm.c

Added default LED settings, LED blinking state fix, Microbit default state set to ON
Changing of the blinking state of an LED is straightforward now. To turn off a MAIN_LED_FLASH_PERMANENT, set the state to MAIN_LED_FLASH, i.e. main_blink_msc_led(MAIN_LED_FLASH)

Added default LED settings, LED blinking state fix, Microbit default state set to ON

---

source/daplink/bootloader/main.c

Changing of the blinking state of an LED is straightforward now. To turn off a MAIN_LED_FLASH_PERMANENT, set the state to MAIN_LED_FLASH, i.e. main_blink_msc_led(MAIN_LED_FLASH)
#477

LED state machine changed

---

source/target/nxp/lpc54608/flash_blob.c

Fix the erase chip function, it was not erasing the whole flash. This should fix Issue https://github.com/ARMmbed/DAPLink/issues/501

Update LPC546xx Flash Algo

---

README.md

The Maxim Epsilon HIC will not be released with DAPLink.

remove Maxim Epsilon HIC

---

source/target/freescale/rapid_iot/target_reset.c

Sharing 1 board ID does not work when running mbed-os

RapidIoT: Need separate board ID for the K64F and KW41Z

---

source/daplink/drag-n-drop/flash_intf.h
source/daplink/drag-n-drop/flash_manager.c
source/daplink/drag-n-drop/iap_flash_intf.c
source/daplink/interface/main.c
source/daplink/interface/target_flash.c
source/daplink/usb2uart/usbd_user_cdc_acm.c

It is implementation dependent that some platforms recovers DP and AP from DAPABORT, some wont. i.e. Cortex-A targets

Added checking to prevent target reset while flashing

---

requirements.txt

This is in preparation for the 0.13 release of pyOCD that will break API compatibility.

Force pyOCD version to 0.12.0

---

docs/DEVELOPERS-GUIDE.md

* Correct  mistake for windows developer
Scripts cammand :
```
$ venv/Scripts/activate
```
can not use in Windows,should it be replaced by :
```
$ venv/Scripts/activate.bat
```
?
* fix syntax mistake of markdown

Fix bug in DEVELOPERS-GUIDE.md

---

source/hic_hal/gpio.h

Raised an error when compiling on uvision IDE v5.17 with ARM compiler v5.06.

Add the missing include file

---

test/run_test.py

If bootloader size bumps up, crc check will fail if bootloader is loaded first.

Test order: load interface before bootloader.

---

source/target/target_family.c

MSD does not work on the BlueNinja board.
usbd_class_init() is defined in usb_lib.c as described below.
```C
void usbd_class_init(void)
{   
#if !(defined(DAPLINK_BL)) &&  defined(DRAG_N_DROP_SUPPORT)
//change descriptors here
if (config_ram_get_disable_msd() == 1 || flash_algo_valid()==0 || target_family_valid()==0){
usbd_if_num -= USBD_MSC_ENABLE;
USB_CONFIGURATION_DESCRIPTOR * usb_conf_desc = (USB_CONFIGURATION_DESCRIPTOR *)USBD_ConfigDescriptor;
```
g_toshiba_tz_family, which is defined in target_family.c, does not have an entry for g_toshiba_tz_family.
So, target_family_valid() returns 0 in case of Toshiba TZ family. MSD descriptors are disabled.

Add an entry for Toshiba TZ family.

---

source/hic_hal/nxp/lpc4322/uart.c

Overflow errors were intermittently seen
Signed-off-by: Mahesh Mahadevan <mahesh.mahadevan@nxp.com>

LPC4322: Increase buff size to 512

---

source/hic_hal/flash_blob.h
source/target/target_board.c
source/target/target_config.h
source/target/target_family.c
test/info.py
tools/flash_algo.py
tools/post_build_script.py

Notes:
1. The flash blob and data structs will be placed at the end of the binary before the crc.
2. Needed a target ram start and end arguments and only support single regions but can easily be extended.
3. Flash blob entry has a default 0x20000000 value but can be specified.
4. Imported flash_algo.py from mbed flash algo script project.

Flash algo binding for no target builds but basically any build

---

records/board/archmax.yaml
source/family/st/stm32f407ve/flash_blob.c
source/family/st/stm32f407ve/target.c

The Arch-MAX target (STM32F407VE) was wrongly defined as 1MB flash rather than 512KB.  This patch fix the issue.
Related to: https://github.com/ARMmbed/mbed-os/issues/9048

Add STM32F407ve for Seeed Arch-MAX

---

source/board/mimxrt1050_evk.c
source/family/freescale/target_reset_mimxrt.c

Undo commits 3384e8c & 1755522. These changes were added to the original MXRT1050 code and cause failures during drag-n-drop operation

MIMXRT1050: Undo changes to make drag-n-drop to work

---

source/board/ep_agora.c

This PR brings the `ep_agora` board configuration closer in line with the configuration of the nRF52840DK.
@flit @0xc0170 @ARMmbed/team-embeddedplanet

Update the ep_agora config to closer match the nRF52840DK config

---

docs/PORT_BOARD.md

Remove the need to request a board ID for custom/non-official dev board as can use the mock feature of `mbedls`.
@0xc0170

Update doc on board ID requirements

---

source/daplink/drag-n-drop/vfs_user.c
source/daplink/drag-n-drop/vfs_user.h

This PR encompasses two changes:
1. Use a table to define the set of standard magic files.
2. Add weak hook functions for user file change notifications and to override or extend magic files.

Refactor magic file handling

---

source/daplink/interface/swd_host.c
source/daplink/interface/swd_host.h
source/daplink/interface/swd_host_ca.c

I would like to call the JTAG2SWD() function from the target_before_init_debug() function

Make the JTAG2SWD function non-static

---

source/daplink/cmsis-dap/DAP.c
source/daplink/cmsis-dap/DAP.h

The range 0x80U-0x9FU of DAP Vendor Command IDs is reserved for generic DAPLink purposes.
For specific Vendor features, the range of DAP command identifiers has been expanded to the range 0xA0U-0xFEU

expand DAP Vendor Command IDs to range 0xA0U-0xFEU

---

source/family/freescale/target_reset_mimxrt.c

This is to bring the hardware to a known state before drag-n-drop.
Failures were seen when running automated mbed-os tests as drag-n-drop would fail when the completed test left the platform in a low-power state. 
Issuing a hardware reset before drag-n-drop would put the platform back to default reset state. 
Signed-off-by: Mahesh Mahadevan <mahesh.mahadevan@nxp.com>

MXRT1050: Issue a hardware reset

---

source/daplink/interface/swd_host.c
source/daplink/interface/swd_host.h
source/daplink/interface/swd_host_ca.c
source/daplink/interface/target_flash.c
source/hic_hal/flash_blob.h

kAlgoVerifyReturnsAddress - Verify function returns address if this flag is set
kAlgoSingleInitType - The Init/UnInit functions contain just return, so can be skipped
kAlgoSkipChipErase - Skip region when erase.act action triggers. ChipErase on Some SPI Flash Memory take much more time that is allowed per drag-n-drop programming.

flashalgo flags are introduced:

---

source/hic_hal/stm32/stm32f103xb/uart.c

some target platform support ISP with uart (such as STM32)，but the ISP need even/odd check，this patch add even/odd check on hic_hal STM32

add support for even/odd check on hic_hal stm32

---

tools/mbedcli_compile.py

In linux, ```not authorized `sys' @ error/constitute.c/```  will be raised when running ```tools/mbedcli_compile.py```. This PR fixed this issue.
Reference: https://stackoverflow.com/questions/55558605/import-im6-q16-not-authorized-error-os-error-constitue-c-writeimage-1037-fo

Fixed bug where not authorized `sys' @ error/constitute.c/ will raised when building in linux

---

source/daplink/daplink.sct

When DAPLINK_RAM_APP2_START is defined, the startup code and data
may be placed in RAM2, which is not guaranteed to work.
Explicitly place main.o and startup_*.o in RAM1.
Signed-off-by: Adrian Negreanu <adrian.negreanu@nxp.com>

always put the main.o code and the startup data in RAM1

---

source/hic_hal/maxim/max32625/uart.c

Added support for wide range of baud rates beyond 115200 for MAX32625 HIC along with other minor changes.
Tested on Windows 10 with MAX32630FTHR and MAX32620FTHR targets.

Rework UART  implementation for MAX32625 HIC

---

source/daplink/cmsis-dap/DAP.c
source/daplink/cmsis-dap/DAP.h
source/daplink/cmsis-dap/dap_strings.h

This change is necessary to fix the version reported for DAP_ID_FW_VER (now DAP_ID_CMSIS_DAP_VER).
Reporting the DAPLink version via the new DAP_ID_PRODUCT_FW_VER.

CMSIS-DAP: support for DAP_ID_PRODUCT_FW_VER

---

source/board/xDot-L151.c

Fixes issues connecting to a MultiTech xDot by holding the STM32L151CC in reset while initiating the SWD connection.  This is done with a custom `target_set_state` function in the xDot-L151 board definition.  Using the existing connect-under-reset option did not solve the connection issues and it was determined that the target must be held in reset prior to calling `swd_init_debug`.

MultiTech XDot - connect under reset

---

source/board/override_96b_nitrogen/IO_Config_Override.h
source/board/override_lpc11u35_6LoWPAN_BorderRouter/IO_Config_Override.h
source/board/override_lpc11u35_reset/IO_Config_Override.h
source/board/override_mtb/IO_Config_Override.h
source/board/override_tiny/IO_Config_Override.h
source/board/override_vbluno51/IO_Config_Override.h
source/hic_hal/nxp/lpc11u35/IO_Config.h

This issue was raised in #502
It seems the `blueninja` had this fix. `mtb_*` and `6LoWPAN_BorderRouter*` only had the fix for the TDO pin.

lpc11u35: fix invalid TDI and TDO pin ports

---

source/hic_hal/nxp/lpc11u35/DAP_config.h

~~This PR consists of two commits.~~
4815db664d2e8e013e5800954888e9aefec5746e fixes #391.
~~e8c0e0c0840376b0a85546d050ccf0cd070c09e6 adds JTAG support for drag-n-drop programming.~~
`PORT_JTAG_SETUP()` has no settings for `PIN_SWCLK_PORT` and `PIN_SWDIO_PORT` pins.
So JTAG had not been working correctly. This patch fixes this issue.
To enable JTAG, `DAP_JTAG=1` needs to be added to `records/board/your_board.yml`.
```YAML
common:
macros:
- DAP_JTAG=1
```
~~Functions for programming flash memory call CMSIS-DAP subroutines, which controls SWD directly.
So DAPLink cannot program via JTAG in spite of the above patch.
We implement the same features via JTAG at `daplink/interface/jtag_host.{c,h}`.
And wrapper functions are added to choose an interface (SWD or JTAG) at …

Add JTAG support into LPC11U35

---

source/hic_hal/nxp/lpc55xx/LPC55S69/drivers/fsl_usart_cmsis.c
source/hic_hal/nxp/lpc55xx/uart.c

This series of patches fix various aspects of the LPC55xx USART CMSIS driver as used by the `uart.c` to expose the USB serial terminal.

LPC55xx: Fix USART0 to USB CDC ACM

---

source/daplink/circ_buf.c
source/daplink/circ_buf.h
source/hic_hal/nxp/lpc55xx/uart.c

Without this patch, transmitting at 921600 baudrate with 8n1 mode yields
to about 49.8KiB/s instead of the theoretical limit of 90 KiB/s. The
reason for this is because between the rising edge of the last data bit
(start of the STOP bit) and the falling edge before the START bit of the
next transfer we observe about 9.7us gap while the minimum is just the
length of a single STOP bit (about 1.1us). This gap is attributed to the
CPU time running the event handler (uart_handler) and scheduling a new
transfer. The performance was measured using a USB-to-UART probe running
with: `picocom -b 921600 /dev/ttyUSB0 | pv >/dev/null` and also looking
at the TX signal on the oscilloscope.
This commit creates two new functions in the circular buffer module that
let you peek into the internal buffer …

LPC55xx: Improve UART TX performance.

---

source/daplink/drag-n-drop/vfs_user.c
source/daplink/util.c
source/daplink/util.h
tools/pre_build_script.py

Builds on #836. It reduces RAM usage by removing `VFS_SECTOR_SIZE`-sized `file_buffer`, but increases a little bit the  code size (~200 bytes on Cortex-M0). It uses a stack-allocated buffer (configurable, default: 128 bytes) for tag expansion.

Support VFS file of arbitrary length

---

source/daplink/drag-n-drop/intelhex.c

- The extraneous store for load_unaligned_record seems to be a compiler issue.
- The exit with HEX_PARSE_OK in the else clause seems very wrong.
If the version does not match one should simply continue to the next line and
not mark the whole buffer as processed.
- The shadow_line content was never used only ever written to.

Fix for micro:bit universal hex support (fixes #847)

---

records/hic_hal/k20dx.yaml
records/hic_hal/k26f.yaml
records/hic_hal/m48ssidae.yaml
records/hic_hal/stm32f103xb.yaml
records/tools/armcc.yaml
source/hic_hal/maxim/max32620/system_max32620.c
source/hic_hal/maxim/max32620/uart.c
source/hic_hal/maxim/max32625/system_max32625.c
source/hic_hal/maxim/max32625/uart.c

We had moved the `--no_unaligned_access` flag to `record/tools/armcc.yaml`. It causes some issues with max32625 HIC.

Fix UART regression with armcc on Max32625

---

source/board/microbitv2/i2c_commands.c
source/board/microbitv2/i2c_commands.h
source/board/microbitv2/microbitv2.c
source/hic_hal/freescale/kl27z/uart.c

-Enabled UART HW overrun interrupt
-Optimized time spent in I2C IRQ handler by moving buffer clearing outside
-Add I2C busy singaling mechanism
-Add I2C ASCII encoding window command feature

microbit specific: Serial and I2C fixes for Microbit V2

---

source/hic_hal/nxp/lpc55xx/uart.c

Some spotted by @tarokajya in #887

Fix a few typos in lpc55xx/uart.c

---

tools/mbedcli_compile.py
tools/progen_compile.py

- Add error exit code when project name provided is invalid.
-  If project_generator doesn't find the project you get an empty generator, it logs something like this, and progen_compile.py exits 0:
`2021-12-08 18:01:30,260                 root ERROR      You specified an invalid project name.`
- Check error code from generate_version_file().

tools: add exit error codes when a project name is invalid or git throws errors

---

source/daplink/cmsis-dap/DAP.c

OpenOCD ends up considering info[1] as capabilities, which in this
case is equal zero.
Signed-off-by: Adrian Negreanu <adrian.negreanu@nxp.com>

DAP: fill the UART capability info only when DAP_UART=1

---

source/hic_hal/nxp/lpc55xx/usbd_LPC55xx.c

Fixes DAPv1 compatibility issue of lpc55s69_if mentioned in https://github.com/ARMmbed/DAPLink/issues/915 .
This also makes it compatible with now old openocd-0.10.0 .

Fix HID interface of LPC55xx HIC

---

records/board/microbit.yaml
records/board/microbitv2.yaml
records/board/microbitv2_nrf52820.yaml
source/daplink/drag-n-drop/vfs_user.c

And remove BOARD_EXTRA_BUFFER vestiges that were not used.

microbit: Set CDC ACM default baud rate for micro:bit v1 and v2.0.

---

source/board/kl27z_microbit_bl.c
source/board/nrf52820_microbit_bl.c

In some cases a micro:bit can get stuck in MAINTENANCE mode (the DAPLink interface could have been overwritten/corrupted, the reset button could have been damaged, etc).
The URL redirect from the help html file in the MAINTENANCE drive has a flag to indicate it came from the bootloader, but because the board ID is `0000` the microbit.org help page cannot identify which board version it was.
Having this board ID can help us pre-select the right DAPLink interface hex file for the user to update/fix their board. 
@flit @mathias-arm I think the DAPLink bootloader board ID has been historically always `0000`, which is one of the reasons we've never touched it. I assume having a different value for the microbit-specific bootloaders should be fine?

microbitv2_bl: Add non-zero board ID to micro:bit DAPLink bootloader.

---

docs/hic/README.md
docs/hic/lpc55xx.md
projects.yaml
records/board/lpc55s69_nrf52840dk.yaml
records/hic_hal/lpc55s69.yaml
source/board/lpc55s69_nrf52840dk.c
source/hic_hal/nxp/lpc55xx/hic_init.c
source/hic_hal/nxp/lpc55xx/uart.c
test/info.py
tools/progen_compile.py

- Adding a test project combining MCU-LINK and nRF52840-DK
- Partial revert of #842 because it impacted negatively validation tests (leading to some assertion failures).
- Reducing CPU clock to 96 MHz (from 150 MHz), internal flash cannot be written at higher speed. Writing to internal flash is needed for configuration and updating bootloader.

A few fixes for LPC55xx HIC

---

source/daplink/circ_buf.c
source/hic_hal/nxp/lpc55xx/uart.c

PR #927 reverted the lpc55xx_hic changes that where sending larger chunks of data since they were hitting an assert during the Validation Tests. The assert was actually backwards, should be checking that the current number of bytes is >= the bytes being removed. In addition to that, the Validation Tests perform baudrate changes during the test with short delays between them and sending/receiving data. Whenever the baudrate or configuration is changed the circular buffers were cleared, but if there was an ongoing TX transfer it would attempt to remove those bytes from the queue once it is done.
This PR re-applies the revert from PR #927, fixes the circular buffer asserts and cancels ongoing TX transfers when clearing the circular buffers.

lpc55xx_hic: Fix circular buffer and re-apply TX performance improvements

---

source/daplink/drag-n-drop/intelhex.c

Fix issue flashing hex files with 32 bytes data records
We encountered this issue for the first time with micro:bit when the MakeCode beta editor started creating Universal Hex files with 32 bytes data records.
With the V2.20 DAPLink factory image, and if automation is enabled, it would cause a `ERROR_WRITE_VERIFY` error.
An example hex file can be downloaded here: [20 chrome flash.zip](https://github.com/ARMmbed/DAPLink/files/7975175/20.chrome.flash.zip)
The issue itself is not directly related to the Universal Hex parsing, as this problem can be replicated with Intel Hex files as well.
This error was caused because there was an out-of-bounds write to the `line.buf` array here, which was changing the value of `load_unaligned_record`, and the change to that flag cascaded into DAPLink …

Fix issue flashing hex files with 32 bytes data records.

---

source/board/microbitv2/i2c.h
source/board/microbitv2/i2c_commands.c
source/board/microbitv2/i2c_commands.h
source/board/microbitv2/kl27z/i2c.c
source/board/microbitv2/microbitv2.c
source/board/microbitv2/nrf52820/i2c.c
source/board/microbitv2/storage_common.c
source/hic_hal/nordic/nrf52820/I2C_Slave_nRF52820.c

This PR only touches the micro:bit specific files to add a feature to the I2C communication with the target: https://github.com/microbit-foundation/spec-i2c-protocol/pull/10
The only exception is commit  2f4b219fe14e447b176064c179caf4a6cc1d4950, which fixes an issue in the nRF52820 hic I2C_Control() function not returning error values for unimplemented features.

micro:bit features: I2C busy flag

---

source/hic_hal/freescale/kl27z/gcc/startup_MKL27Z4.S

Fixes the issue where GCC builds do not call the expected ISR:
https://github.com/ARMmbed/DAPLink/blob/c782a5ba907377658bc28aa8d132a0fa44543687/source/board/microbitv2/kl27z/power.c#L91

kl27z_hic: Change GCC GPIO port C+D IRQ handler name to match armcc.

---

source/hic_hal/freescale/kinetis.ld
source/hic_hal/freescale/kl27z/armcc/startup_MKL27Z4.s
source/hic_hal/freescale/kl27z/gcc/startup_MKL27Z4.S

- Sets the ROM bootloader settings in the GCC builds to mirror armcc
- For both GCC and armcc it changes the default (non-microbit) flash config for `FOPT` from `0x39` to `0x3B`
- The main difference is that `BOOTPIN_OPT` is set to `1`, so it doesn't trigger the ROM bootloader if the `BOOTCFG0` pin is grounded (which in micro:bit is connected to TP1, to trigger the ROM bootloader)
- The original GCC code had set this value to `0x3F` which wasn't quite right either
- It also updates the GCC and armcc DAPLink Interface builds to not include the flash config data, which right now is being unnecessarily added to flash at address 0x8400
- The flash config goes into address 0x400, so it only needs to be set in the DAPLink bootloader builds

kl27z_hic: Update GCC flash & ROM bootloader config and tweak non-microbit value

---

source/daplink/cmsis-dap/dap_strings.h

fix lpc11u35 not found in mdk ,fw >0254
Fixes #977. Some tools (including some versions of MDK) require "CMSIS-DAP" to be present in product name. This has been an issue since DAPLink added support for bulk interface (DAPv2) in v0254.

Penjun71 patch daplink for mdk

---

records/hic_hal/max32625.yaml

It was worked but after rebasing repository with upstream ones the build break. So that this changes applied.
Build error:
source\hic_hal\maxim\max32625\armcc\startup_max32625.S file requires daplink_defaults.h file
Signed-off-by: Sadik.Ozer <sadik.ozer@analog.com>

Add source/daplink in assembly include path

---

tools/generate_flash_algo.py

1. generate `#define` instead of `const uint32_t`;
1. add the missing field `algo_flags`.

fix flash algo generation script

---

source/daplink/drag-n-drop/intelhex.c

Optimisation only applied to the `intelhex.c` file.
In my tests with micro:bit V2, when build with GCC v10.3, this can improve flashing time (rsync a .hex file with 512Kbs of flash data) by around 0.7-0.8 seconds.
For additional info, building the entire project with `-O3` shaved another second-ish of flashing time, but that might be too much of a change/risk (it's likely it can also increase binary size, but I didn't really checked those numbers). I couldn't easily find another single file in the USB or vfs layer that significantly improved times on their own, just a tiny bit here and there, but the `intelhex.c` file is significant enough where this might be worth doing.
The specific compiler incantations have been copy/pasted from the `SW_DP.c` file: …

intelhex: Increase optimisation level to O3.

---

source/usb/bulk/usbd_bulk.c

CMSIS-DAPv2: blink LED on bulk interface activity

---

source/board/artemis_dk.c
source/board/microbit.c
source/board/microbitv2/microbitv2.c
source/daplink/cmsis-dap/DAP_queue.c
source/usb/bulk/usbd_bulk.c
source/usb/hid/usbd_user_hid.c

A continuation from this PR, opened from my account fork so that it can be edited by maintainers:
- https://github.com/ARMmbed/DAPLink/pull/1018
Implemented the suggestion from https://github.com/ARMmbed/DAPLink/pull/1018#issuecomment-1480288695 and the final result is:
Moves `usbd_hid_no_activity()` hook from `usbd_user_hid.c` to `DAP_queue.c` and renames it to `DAP_activity_blink()`.
In this new location it can be used to skip HID LED blinking in traffic from USB bulk as well.
Adds the default behaviour to the weak function to skip HID blink of DAP serial & MSD activity.
Removes customised hooks in the artemis & micro:bit projects as they are no longer needed.
The logic in the hook has been reverted from a "negative check" to a "positive check" (before `usbd_hid_no_activity()` returned …

Update hook to skip blinking on WebUSB HID serial traffic.

---

.github/workflows/linux.yml
.github/workflows/pr.yml
.github/workflows/windows.yml

- Add new workflow for PR builds which is much faster and complete.
- Switch download of GCC toolchain to `carlosperate/arm-none-eabi-gcc-action@v1` action from @carlosperate / @microbit-carlos.
- Fix issues with `ccache` persistence across builds.
- Update other dependencies

Update to Github Actions builds

---

source/hic_hal/nxp/lpc55xx/usbd_LPC55xx.c

Fix LPC55 HIC missing out on a setup packet

---

source/hic_hal/maxim/max32625/DAP_config.h

When code attempted to release the ports by placing them into Hi-Z mode, it would first clear the out register (so that weak pull-up would be disabled) then made the switch to Hi-Z.  Since the signals were initially in output mode, clearing the out register caused a low pulse on the pins.  One of the pins is the RESETN line which caused an unwanted device reset.
This PR changes the code to use the "NORMAL_HI_Z" mode that the MAX32625 supports.  This mode places the pins in Hi-Z (no pull-up) regardless of the state of the out register.
See section 5.4.3 of the [MAX32625 user guide](https://www.analog.com/media/en/technical-documentation/user-guides/max32625-users-guide.pdf) for the I/O modes supported.

Modified GPIO code to prevent low pulse when switching to Hi-Z mode.

---

.github/workflows/linux.yml
.github/workflows/pr.yml
.github/workflows/windows.yml

`actions/upload-artifact@v3` stopped working on January 30th 2025: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
Also took the opportunity to update the other GH actions to the latest version.

ci: Update version of GH official actions to fix deprecation error.

---

source/daplink/cmsis-dap/DAP_vendor.c
source/daplink/drag-n-drop/vfs_manager.c

Currently flashing a Universal Hex in "segments" or "blocks" format via WebUSB does not work.
This PR sends to the file streamer blocks of the same size as the VFS sector size, which is what `vfs_manager` does and some stream formats expect, like Universal Hex and in the future UF2.
This could have been implemented inside `file_stream` instead, but this way it mirrors what the MSC side is doing, buffering the 64 byte packets into 512-byte sectors before passing it to `vfs_manager`, which then sends it to `file_stream`.
One constrain is that DAPLink doesn't know when the last DAP.js `ID_DAP_MSD_Write` packet is sent, so we need to flush whatever is left in the buffer on `ID_DAP_MSD_Close`. So the "close" response could contain an error writing the last buffer.
There is also a memory hit, …

dap_vendor: Buffer MSD_Write packets into 512-byte blocks.

---

source/daplink/bootloader/main_bootloader.c
source/daplink/interface/main_interface.c

Tiny cleanup of macro.
Initially included to control how long it would take for the MSC drive to reconnect after being ejected, as shown in ca7276dedb781c842dec7798c4fb165f3372fe7e.
That feature was moved and updated the VFS manager as shown in 3c733e851ea6d453b6834232466f7d2b17fff1b6.

Remove unused `USB_CONNECT_DELAY` macro.

---

.github/workflows/linux.yml
.github/workflows/pr.yml
.github/workflows/windows.yml
docs/DEVELOPERS-GUIDE.md
records/tools/gcc_arm.yaml
source/daplink/stubs.c

- Fixes #1040
- Updates CI to use Arm GNU Toolchain version 13.2.Rel1 (builds on #1042)

Support for newer Arm GNU Toolchain versions
