ARMmbed/DAPLink

test/info.py
I scratched my head quite a bit when I first saw this map. Only after learning the code did it make sense.
=> Document TARGET_NAME_TO_BOARD_ID

docs/DEVELOPERS-GUIDE.md, records/tools/uvision.uvproj.tmpl, tools/build_release_uvision.bat, tools/launch_uv4.bat, tools/launch_uvision.bat, tools/post_build_script.bat, tools/pre_build_script.bat, tools/pre_build_script.py
The daplink post/pre scripts invoked by the uVision builds lacked proper error checking and reporting. The projects, in turn, didn't care of the scripts failed. Both of these deficiencies are fixed by this PR. Also improved script output--removed a lot of clutter.
Also added script for launching uVision in the proper environment from the cmdline. Updated documentation.
=> Project improvements

docs/MSD_COMMANDS.md, source/daplink/drag-n-drop/vfs_user.c
Add a mass storage command to erase flash contents on the target.
=> Add support for MSD command 'erase.act'

tools/combine_images.py
- Added --output_bin_file argument to optionally write a binary copy of the output file.
- Expanding ~ and ~user in all specified paths.
=> Improvements to combine_images.py

source/hic_hal/freescale/k20dx/uart.c, source/hic_hal/freescale/kl26z/uart.c, test/daplink_board.py, test/serial_test.py
Fix uart settings change problem on k20dx and add a test for this.
=> Fix k20dx uart setting change

docs/PORT_BOARD.md
Update PORT_BOARD.md to fix file name mistake.
=> Update docs to change into.py to info.py

projects.yaml, records/board/ssci_chibi.yaml, source/board/hrm1017.c, source/board/ssci1114.c, source/board/ssci_chibi.c, source/board/sscity.c, test/info.py
Updated #136 and moved it here.
=> Add files to support the board id 1021

projects.yaml, records/board/xDot-L151.yaml, source/board/xDot-L151.c, source/target/st/xDot-L151/flash_blob.c, source/target/st/xDot-L151/target.c, source/target/st/xDot-L151/target_reset.c, test/info.py
Add initial support for the MTS xDOT target.
=> Add support for MTS xDot with ST L151 target

records/tools/version.yaml
Bump the version from 0241 to 0242.
=> Bump version to 0242

test/msd_test.py, test/test_daplink.py
We need the address offset when comparing the loaded data.
=> [Test] Exctracting starting address from hex file

projects.yaml, records/board/cocorico.yaml, source/board/cocorico.c, test/info.py
=> Added cocorico platform

source/hic_hal/atmel/sam3u2c/usbd_ATSAM3U2C.c
When a SETUP packet comes immediately after a control transfer with a data in stage there is a chance that the SETUP packet will be corrupted by the OUT packet processing. This is because at the time the interrupt occurred the register UDPHS_EPTSTA contained information about the OUT packet, but in the read inside USBD_ReadEP this register contains information about the SETUP transfer that occurred. Because of this the SETUP packet is treated like an OUT packet.
This patch fixes this problem by recording the value of UDPHS_EPTSTA and using this value inside USBD_ReadEP rather than reading from the hardware register again. This ensures the value does not change the initial read and the call to USBD_ReadEP.
This problem can be reproduced by adding "os_dly_wait(1);" at the start of …
=> atsam3u - Prevent dropped USB SETUP packets

source/hic_hal/nxp/lpc11u35/gpio.c
Allow start_bl.act to switch the lpc11u35 into ISP mode. Since there
is no way to exit ISP mode from the host PC, setup the watchdog to
trigger a reset which starts DAPLink after ~30 seconds.
=> Add initial automation support for lpc11u35

records/tools/version.yaml
Bump the version from 0242 to 0243.
=> Bump version to 0243

source/daplink/interface/swd_host.c
If for some reason a targets DP won't powerup, DAPLink will get stuck in a loop waiting for this to occur. Add a timeout to prevent this timeout and to allow DAPLink to boot normally.
This problem can be reproduced on the FRDM-KW24D if target firmware sets pin PTB19 low immediately after boot.
CC: @flit
=> Prevent lockup when target DP won't powerup

test/info.py
Add the ublox c027 interface firmware to list of images to be released.
=> Add ublox c027 interface to release

source/daplink/drag-n-drop/flash_decoder.c, test/daplink_board.py, test/test_daplink.py
Improve CI stability and add more robust checking in tests
=> Ci stability fixes

source/target/nordic/nrf5x/target.c
Fix sector count setting, looks like a typo to me.
=> Fix nrf5x sector count

source/hic_hal/nxp/lpc11u35/uart.c
If flow control is on on the lpc11u35 then the code can get stuck indefinitely in uart reset waiting for all the bytes to get sent. To prevent this, temporarily switch the UART to loopback mode so it can be drained even if flow control is on.
=> Fix lockup on lpc11u35 when flow control is on

test/daplink_board.py
Test framework updates related with IF/BL mode switch and re-mount mechanism.
Work In Progress / Do Not Pull Yet..
=> Test: IF<->BL switch + remount [work in progress]

tools/test_loop.sh
=> Simple shell script to loop local tests until (intermittent) fail.

projects.yaml, records/board/ro359b.yaml, source/board/ro359b.c, test/info.py
=> Added RO359B, board id 1022

projects.yaml, records/board/FF1705_L151.yaml, source/board/FF1705_L151.c, test/info.py
* compiling and programming ok
* board id set to 8080 -> confirmed from mbedos
* test info added.
* rebased and squashed
=> new target added L-TEK FF1705

source/board/lpc54114xpresso.c, source/board/lpc54608xpresso.c
Point to the newly created mbed pages
Signed-off-by: Mahadevan Mahesh <Mahesh.Mahadevan@nxp.com>
=> Update target URL for LPC54114 and LPC54608

records/tools/version.yaml
=> Bump release version 243 -> 244.

projects.yaml, records/board/mbed_cloud_connect.yaml, source/board/mbed_cloud_connect.c, source/target/st/stm32f439zi/flash_blob.c, source/target/st/stm32f439zi/target.c, test/info.py
Add the flash algo for the stm32f439zi, along with the board support for mbed cloud connect board.
=> Add support for the mbed cloud connect board

source/board/vbluno51.c
The VBLUno51 has platform link at https://os.mbed.com/platforms/VBLUNO51/
=> Use new platform link

test/info.py
Add the ncs36510 firmware to the public release package.
=> Add the ncs36510 to the released firmware list

tools/build_release_uvision.bat, tools/launch_uvision.bat
=> Updated uVision bat scripts to autodetect UV4.

projects.yaml, records/board/ff_lpc546xx.yaml, source/board/ff_lpc546xx.c, test/info.py
add new target L-Tek FF-LPC546XX
board id: 8081
=> ff_lpc546xx: add new target

projects.yaml, records/board/96b_nitrogen.yaml, source/board/96b_nitrogen.c, source/board/override_96b_nitrogen/IO_Config_Override.h, source/target/nordic/target_reset_nrf52.c, test/info.py
Board details available at https://www.96boards.org/product/nitrogen
Signed-off-by: Ricardo Salveti <ricardo@opensourcefoundries.com>
=> Add 96boards Nitrogen, board id 0x9014

source/hic_hal/nxp/lpc4322/flash.c, source/hic_hal/nxp/lpc4322/read_uid.c
Fix for Issue 340
Signed-off-by: Mahesh Mahadevan <Mahesh.Mahadevan@nxp.com>
=> LPC4322 Protect IAP function calls

source/board/frdmk64f.c, source/daplink/interface/target_flash.c, source/hic_hal/flash_blob.h, source/hic_hal/target_config.h, source/target/freescale/k64f/flash_blob.c, source/target/freescale/k64f/target.c
Sector erase will be added for all targets at the same time at the request of @sg-.
=> Revert K64F sector erase

projects.yaml, records/board/mtb_murata_abz_078.yaml, records/board/mtb_mxchip_emw3166.yaml, records/board/mtb_nina_b112.yaml, records/board/mtb_wise1510.yaml, records/board/mtb_wise1530.yaml, records/board/mtb_wise1570.yaml, source/board/mtb_murata_abz_078.c, source/board/mtb_mxchip_emw3166.c, source/board/mtb_nina_b112.c, source/board/mtb_wise1510.c, source/board/mtb_wise1530.c, source/board/mtb_wise1570.c, source/board/override_mtb/IO_Config_Override.h, source/target/st/stm32f412re/flash_blob.c, source/target/st/stm32f412re/target.c, source/target/st/stm32l082cz/flash_blob.c, source/target/st/stm32l082cz/target.c, source/target/st/stm32l443rc/flash_blob.c, source/target/st/stm32l443rc/target.c, source/target/st/stm32l486jg/flash_blob.c, source/target/st/stm32l486jg/target.c, test/info.py
Add target and board info for the following boards:
WISE-1510
WISE-1530
WISE-1570
=> Add support for module test boards

records/tools/version.yaml
Bump the version from 0244 to 0245.
=> Bump version to 0245

projects.yaml, records/board/mtb_laird_bl652.yaml, records/board/mtb_rak811.yaml, source/board/mtb_laird_bl652.c, source/board/mtb_rak811.c, source/target/st/stm32l151cb/flash_blob.c, source/target/st/stm32l151cb/target.c, test/info.py
Add the Laird BL652 and RAK811 modules.
=> Add more MTB boards

test/info.py, test/mbedapi.py
Update info.py and the compile API script so it now works correctly.
=> Fix compile API

source/target/freescale/target_reset_Kseries.c, source/target/freescale/target_reset_Lseries.c
This reverts commit 17f192184fcdec38f68c425d1758070da7733504.
=> Revert "Update Kinetis code to init debug without reset"

source/daplink/cmsis-dap/DAP_vendor.c
Add DAP commands to:
- reset a target
- open mass storage device stream
- close mass storage device stream
- write to a mass storage device
This PR allows to flash a program on a board using flashing algorithms and memory maps from DAPLink instead of providing them in a client.
@c1728p9 @thegecko
=> Add dap commands for flashing the target using MSD

.gitignore
Ignore the .vscode folder
Signed-off-by: Findlay Feng <i@fengch.me>
=> .gitignore: add vscode editor

source/daplink/drag-n-drop/vfs_user.c
Added a overflow check on 512 buffer after expanding special characters
=> Added support for URL in DETAILS.TXT

records/board/gr-lychee.yaml, records/board/gr-peach.yaml, source/target/renesas/validation_rza.c
Fixed the issues https://github.com/ARMmbed/DAPLink/issues/454
=> Fixed duplicate file name

source/board/microbit.c
This new URL will give a 404 at the moment, but we are about to update the website to fix that.
=> microbit: Update URL to microbit.org website

test/serial_test.py
=> Added pyserial init params and reset buffers before test

tools/build_release_uvision.bat, tools/package_release_files.py, tools/update_yml.py
For release procedure, extend package_release_files.py to generate update.yml
=> Added support for update.yml generation on release

tools/package_release_files.py, tools/update_yml.py
Note: this standard yaml format is not currently supported by the gh-pages parser and a non-standard generator being used to generate update.yml
=> Change names for bins, added zip generation, put update.yml file to same output directory

source/daplink/interface/swd_host.c
MTB_ADV_WISE_1530 issues when the target is in invalid state, AP writes fail. 
#467
=> Try to do a rewrite when AP fails after a reset.

tools/package_release_files.py
=> Fix multiple board configurations from a single project name.

test/daplink_board.py
In windows, the next remount from IF to BL can be fast that tracking the drive can be time critical
=> Check first if the board is already remounted by checking mode change and remount count

records/board/microbit.yaml, source/hic_hal/atmel/sam3u2c/usb_config.c, source/hic_hal/freescale/k20dx/usb_config.c, source/hic_hal/freescale/kl26z/usb_config.c, source/hic_hal/nxp/lpc11u35/usb_config.c, source/hic_hal/nxp/lpc4322/usb_config.c
Tested with uVision and IAR to have no effect on debugger (ids and download).
=> Added option to customize usb product string

source/board/microbit.c, source/daplink/bootloader/main.c, source/daplink/bootloader/main.h, source/daplink/cmsis-dap/usbd_user_hid.c, source/daplink/interface/main.c, source/daplink/interface/main.h
This happens in WebUSB polling the UART for reads and the returned length 0 meaning no data
=> HID LED patch to stop flashing on UART poll 

source/daplink/drag-n-drop/vfs_manager.c
EDGE download has this symptom.
=> Size can zero in browser download, any size transferred can be a file optional finish

projects.yaml, records/board/mtb_mts_dragonfly.yaml, records/board/mtb_mts_xdot.yaml, records/board/mtb_ublox_odin_w2.yaml, source/board/mtb_mts_dragonfly.c, source/board/mtb_mts_xdot.c, source/board/mtb_ublox_odin_w2.c, test/info.py
https://jira.arm.com/browse/IOTCORE-486
=> Added boards mtb_ublox_odin_w2, mtb_mts_dragonfly, and mtb_mts_xdot

source/daplink/interface/swd_host.c
Cause by reset, or download to target abort
=> Added DAPABORT logic when initialization fails

docs/DEVELOPERS-GUIDE.md, tools/build_release.bat, tools/mbedcli_compile.py, tools/mbedcli_tools/__init__.py, tools/mbedcli_tools/generate_custom_cli_files.py, tools/mbedcli_tools/generate_mbedcli_files.py, tools/mbedcli_tools/generate_mbedignore.py, tools/mbedcli_tools/mbedcli_run.py
- Added verbosity on mbed compile support 
- Update guide on using mbedcli support
=> Added verbosity on mbed compile support

source/hic_hal/atmel/sam3u2c/sam3u2c.h, source/hic_hal/nxp/lpc4322/lpc43xx_cgu.h, source/hic_hal/nxp/lpc4322/lpc43xx_scu.c, source/hic_hal/nxp/lpc4322/system_LPC43xx.c, source/hic_hal/nxp/lpc4322/system_LPC43xx.h, source/target/onsemi/ncs36510/target_reset.c, source/target/realtek/rtl8195am/target_reset.c, tools/package_release_files.py, tools/pre_build_script.py
This should address issue https://github.com/ARMmbed/DAPLink/issues/523
=> fix linux build errors

source/daplink/drag-n-drop/virtual_fs.c
=> Make storage drive persistent from host point of view

source/daplink/drag-n-drop/vfs_manager.c, source/daplink/drag-n-drop/virtual_fs.c
Added size check, large size flashing in mac causing size revert.
=> Fix persistent storage to actual files created

source/daplink/validation.c, source/hic_hal/target_config.h
=> Added multiple ram and flash region check

requirements.txt, test/daplink_board.py, test/hid_test.py, test/msd_test.py, test/stress_tests/hid_usb_test.py
Updated the pyOCD usage in test scripts to support the changes to the Python API.
Pinned pyOCD to version 0.15.0.
=> Updated pyOCD API usage

source/board/mtb_ublox_odin_w2.c, source/daplink/interface/swd_host.c, source/daplink/interface/swd_host.h, source/daplink/interface/swd_host_ca.c
Fixes stm issues that cannot recover from bad binaries if not under reset.
=> Assert reset when enabling debug or under reset support

docs/USERS-GUIDE.md
Make initial copy edits to file.
=> Edit USERS-GUIDE.md

requirements.txt, test/hid_test.py
Match the function name with pyocd tools.
=> Rename reset_stop_on_reset() to reset_and_halt()

source/daplink/settings/settings_rom.c
Will trigger reset and run of the binary after flashing
=> Change default rom settings auto_rst to 1.

projects.yaml, records/board/wio3g.yaml, records/board/wiobg96.yaml, source/board/wio3g.c, source/board/wiobg96.c, source/target/st/stm32f439zi/target_reset_f439.c, test/info.py
=> Adding Wio 3G and BG96

source/hic_hal/nxp/lpc11u35/usbd_LPC11Uxx.c
=> Wait for buffer status on lpc11u35 EP read

source/daplink/drag-n-drop/flash_decoder.c, source/daplink/drag-n-drop/flash_manager.c, source/daplink/drag-n-drop/intelhex.c
Removed address > flash_end as end of flashing. Non-increasing address will cause a sector setup, page erase if supported.
closes #506
=> Added non-sequential non-increasing address support

source/daplink/drag-n-drop/flash_intf.h, source/daplink/drag-n-drop/flash_manager.c, source/daplink/error.c, source/daplink/error.h, source/daplink/interface/target_flash.c, source/family/nxp/lpc55S6X/target.c, source/hic_hal/target_config.h
Note, boundary for addresses should be atleast sector size
Closes #605
=> Support for multiple flash algo.

.editorconfig, CONTRIBUTING.md, README.md
This was sorely needed…
Also added an `.editorconfig` file that sets the indent style and whitespace options.
=> Add contribution guidelines

docs/DEVELOPERS-GUIDE.md
add a way to generate only one specific project,but not all project
=> Xieyang ly patch project generate

projects.yaml, records/board/wio_emw3166.yaml, source/board/wio_emw3166.c, test/info.py
Add Seeed Wio EMW3166 target (board_id = 9017)
cc @ARMmbed/team-seeed
=> Add Seeed Wio EMW3166 target

source/rtos_none/SysTick_Handler.c, source/rtos_none/cmsis_os2_port.c
=> rtos: fix systick inclusion

source/family/freescale/rapid_iot/target.c, source/family/nordic/nrf5x/target.c
These constructions seem to be typos
=> Fix sector_info_length calculation

docs/MSD_COMMANDS.md, source/daplink/cmsis-dap/DAP_vendor.c, source/daplink/drag-n-drop/flash_manager.c, source/daplink/drag-n-drop/vfs_user.c, source/daplink/settings/settings.c, source/daplink/settings/settings.h
Switching between chip erase/sector erase by .act files and DAP Vendor Command.
=> Switching between chip erase/sector erase

requirements.txt, test/hid_test.py, test/msd_test.py, test/usb_msd.py
Update pyocd to 0.28.* and progen to 0.10.*.
- Updated pyocd API usage in test suite.
- Removed flash page programming test from `hid_test.py` since it doesn't test anything more than does initially programming the test firmware.
=> Update pyocd and progen versions

source/hic_hal/nxp/lpc4322/daplink_addr.h, source/hic_hal/nxp/lpc4322/usb_config.c
This pull-request depends on https://github.com/ARMmbed/DAPLink/pull/743
=> lpc4322: enable high-speed usb

requirements.txt, tools/flash_algo.py
Fix was requested in this issue: https://github.com/ARMmbed/DAPLink/issues/778
=> Fix flash_algo.py to properly support both Python2 and Python3

source/daplink/drag-n-drop/vfs_user.c
Fixes https://github.com/ARMmbed/DAPLink/issues/787
=> Fix vfs_user.c to properly get magic file index

source/hic_hal/nxp/lpc55xx/uart.c
`uart_write_data()` uses a circular buffer to enqueue next TX bytes and
a single `cb_buf.tx` byte for the "current" byte it is sending. This
function was always calling `USART_INSTANCE.Send` without checking
whether a transfer was already in progress, which would cause the
fsl_uart_cmsis.c to override the current transfer if there was one in
progress. This would cause the next byte in the circular buffer (the
one returned by `pop`) to be discarded when `uart_write_data()` is
called and there is already data pending in the circular buffer. This
bug can be reliably reproduced when issuing multiple writes on the
/dev/ttyACM0 device on a short period of time.
This patch fixes the problem by adding a flag that tells whether the
current transfer is still ongoing or not. At the moment, since all …
=> LPC55xx: Fix uart_write_data() with pending transfers.

tools/generate_config.py
Testes with Python 2.7 and 3.6 to create the same output file.
=> Python 3 updates for `generate_config.py` script.

source/daplink/drag-n-drop/intelhex.c
Addresses an performance regression mentioned in #847
@microbit-carlos
=> Recover performance for block-aligned uhex images (fixes #847)

projects.yaml, records/board/max32660evsys.yaml, source/board/max32660evsys.c, source/family/maxim/max32660/flash_blob.c, source/family/maxim/max32660/target.c, source/family/maxim/max32660/target_reset_max32660.c, source/target/target_family.c, source/target/target_family.h, test/info.py
Signed-off-by: Sadik.Ozer <Sadik.Ozer@maximintegrated.com>
=> Add MAX32660EVSYS board

projects.yaml, tools/projects_sort.py
Sorted according to Python sort(), script provided
=> Sorting projects in projects.yaml

docs/hic/lpc55xx.md, projects.yaml, records/board/mcu_link.yaml, source/board/mcu-link.c, source/hic_hal/nxp/lpc55xx/DAP_config.h, source/hic_hal/nxp/lpc55xx/IO_Config.h, source/hic_hal/nxp/lpc55xx/gpio.c
- Support for nRESET as reset button
- Detect MCU-LINK-PRO  and support additional LEDs
=> lpc55xx_hic: add support for MCU-LINK-PRO and nRESET

requirements.txt
=> python: update pyOCD (and other python dependencies)

source/board/microbitv2/kl27z/pwr_mon.c, source/board/microbitv2/microbitv2.c
Created as draft to wait for @microbit-carlos testing with armcc.
=> Microbit v2: Add HW timer for delays instead of busy "for" loops

source/hic_hal/nordic/nrf52820/uart.c
Similar issue as merged in #927
=> Revert "Improve UART TX performance" for nrf52820

tools/combine_images.py
And maintains compatibility with Python 2.7.
=> tools: Python 3 updates for `combine_images.py`.

source/board/udb/lib/nlbacktrace/source/nlbacktrace_udb.c
The file has been open-sourced so I'm just cleaning up this comment.
=> Remove outdated license comment
